Wander-Scout/WanderScoutProject

README.md
Adding more details to how customer reviews will be generated.
=> docs: updating readme details

README.md
=> docs: fixing README.md

README.md, wanderscout/settings.py
=> docs: adding pws link

README.md
changed "Happenings" to "events"
=> testing for hh branch

tourist_attraction/models.py
=> feat: adding half the models for tourist attraction

tourist_attraction/models.py
Creating model for tourist attraction
=> feat: creating model for tourist attraction

static/css/global.css
=> style: adding global.css file

image_display/views.py
removing the need for the external name space remover
=> bugfix: removing dependency on yahoo, made own namespace function

authentication/urls.py, authentication/views.py, main/templates/login.html, main/templates/register.html
register feature, register.html, modified login.html, urls.py,
=> feat:added a register feature

main/templates/customer_reviews.html, main/urls.py, main/views.py
feat: fix the customer reviews
=> feat: fix the customer reviews

main/templates/login.html
style: fix formatting of login page
=> style: fix formatting of login page

main/templates/register.html
style: add styling for register
=> style: add styling for register

authentication/apps.py, authentication/decorators.py, authentication/signals.py, authentication/urls.py, authentication/views.py, main/templates/register.html, templates/navbar.html, wanderscout/settings.py
Fixed user roles to finally give certain access to different user types
Created a way to determine admin or user authorization
created decorators to integrate to other pages
=> feat: improving authentication to discern user and admin, auto generate admin if one doesnt exist

authentication/signals.py
forgot to mention logout function was also finished and placed in navbar
=> bugfix: automatically create tourist group

tourist_attraction/templates/attraction_cards.html, tourist_attraction/urls.py, tourist_attraction/views.py
Rather long html file please review it incase any changes need to be made
=> feat: adding ajax, post, delete functions to tourist attraction, restricting to only admin use

templates/navbar.html
feat: fixed some features for the navbar
=> feat: fixed some features for the navbar

authentication/decorators.py, main/urls.py, main/views.py, restaurant/tests.py, restaurant/views.py
FIXED:
Decorators in authentication
ImageModel issue = changed to RSSItem
removed admin url in main/urls.py
adding @admin_only to restaurant/views.py
=> fix:fixing authentication, main, restaurant

authentication/tests.py
Added:
Unit test for authentication app
=> fix: added an unit test for authentication app

authentication/forms.py, authentication/views.py, restaurant/tests.py
ADDED:
strip tags to authentication
FIXED:
restaurant unit tests
=> fix: restaurant tests and added strip tags to authentication

authentication/decorators.py, authentication/forms.py, authentication/templates/profile.html, authentication/templatetags/custom_filters.py, authentication/urls.py, authentication/views.py
ADDDED:
comments for authentication
=> style: added comments to authentication

authentication/templates/profile.html, main/forms.py, main/models.py, main/templates/customer_reviews.html, main/templates/home_page.html, main/templates/login.html, main/templates/register.html, main/tests.py, main/urls.py, main/views.py, restaurant/templates/restaurant_cards.html, restaurant/templates/restaurant_detail.html, shopping_cart/templates/cart.html, templates/base.html, templates/navbar.html, tourist_attraction/templates/attraction_cards.html, tourist_attraction/templates/attraction_detail.html
=> feat: finishing

restaurant/templatetags/custom_tags.py, restaurant/views.py
ADDED COMMENTS
⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠋⠉⠁⠄⠄⠈⠙⠻⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⠟⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠙⢿⣿
⣿⣿⣿⣿⡿⠃⠄⠄⠄⢀⣀⣀⡀⠄⠄⠄⠄⠄⠄⠄⠈⢿
⣿⣿⣿⡟⠄⠄⠄⠄⠐⢻⣿⣿⣿⣷⡄⠄⠄⠄⠄⠄⠄⠈
⣿⣿⣿⠃⠄⠄⠄⢀⠴⠛⠙⣿⣿⡿⣿⣦⠄⠄⠄⠄⠄⠄
⣿⣿⠃⠄⢠⡖⠉⠄⠄⠄⣠⣿⡏⠄⢹⣿⠄⠄⠄⠄⠄⢠
⣿⠃⠄⠄⢸⣧⣤⣤⣤⢾⣿⣿⡇⠄⠈⢻⡆⠄⠄⠄⠄⣾
⠁⠄⠄⠄⠈⠉⠛⢿⡟⠉⠉⣿⣷⣀⠄⠄⣿⡆⠄⠄⢠⣿
⠄⠄⠄⠄⠄⠄⢠⡿⠿⢿⣷⣿⣿⣿⣿⣿⠿⠃⠄⠄⣸⣿
⠄⠄⠄⠄⠄⢀⡞⠄⠄⠄⠈⣿⣿⣿⡟⠁⠄⠄⠄⠄⣿⣿
⠄⠄⠄⠄⠄⢸⠄⠄⠄⠄⢀⣿⣿⡟⠄⠄⠄⠄⠄⢠⣿⣿
⠄⠄⠄⠄⠄⠘⠄⠄⠄⢀⡼⠛⠉⠄⠄⠄⠄⠄⠄⣼⣿⣿
⠄⠄⠄⠄⠄⡇⠄⠄⢀⠎⠄⠄⠄⠄⠄⠄⠄⠄⠙⢿⣿⣿
⠄⠄⠄⠄⢰⠃⠄⢀⠎⠄⠄⠄⠄⠄⠄⠄⠙⢿⣿⣿⣿⣿
=> style: added comments

README.md
=> style: fix contents of README

authentication/urls.py, authentication/views.py, wanderscout/settings.py
For flutter login and register integration
=> Feat: adding login and register flutter integration

restaurant/urls.py, restaurant/views.py
added edit sm WIP delete yg gagal
=> feat: edit on flutter(restaurant)
